### ISSUE TITLE
Wrap project to package or module

### ISSUE THREAD

**Issue by raffifu** [raffifu/pokemon-truecolor#2]
Goal: Anyone can install this program using `pip`

**Comment by Veerhan-glitch** [comment]
Hey i am working on this, can you pls assign me the issue

**Comment by raffifu** [comment]
Hii, i'm not actively maintain this repo. But sure you can work on this issue

**Comment by Veerhan-glitch** [comment]
Hey i am almost done, now i just need you to upload it, for that i need an account under which it will be don so should i just do it under mine or tell u the process and u do it?

also thx for assigning me even when u r not actively maintain this repo.

**Comment by raffifu** [comment]
You can open Pull Request if there's an update to the repo and also put the step-by-step on the PR. Thank you for working in this issue
